---
# vars file for maven_install

maven_version: "3.9.6"
maven_download_url: "https://dlcdn.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
maven_install_dir: "/opt/mvn-{{ maven_version }}"
java_home: "/usr/lib/jvm/java-17-openjdk-amd64"
java_package: "openjdk-17-jre-headless"
